### ISSUE TITLE
Ошибка метода ПрочитатьJSON

### ISSUE THREAD

**Issue by HardAndHeavy** [oscript-library/json#2]
Не знаю на сколько критическая, но всё же.

При попытке прочитать строку содержащую "\update" вылетает ошибка: "Ошибка в строке: 692 / JSON: Некорректный формат строки в позиции"

Пример кода на OneScript:
```
#Использовать json

Процедура ВыполнитьКоманду()
	
	текстНастроек =
	"{
	|	""myString"": ""C:\update_for_my_base.epf""
	|}";
	
	ЧтениеJSON = Новый ПарсерJSON;
	параметрыИзФайла = ЧтениеJSON.ПрочитатьJSON(текстНастроек,,,Истина);
	
	Сообщить(параметрыИзФайла["myString"]);

КонецПроцедуры

ВыполнитьКоманду();
```

Если файл переименовать в "_update", что даст "\_update", то ЧтениеJSON отработает корректно.

Понимаю, что частный случай, но может рядом есть ещё подобная ошибка.

**Comment by dmpas** [comment]
`C:\\update_for_my_base.epf`
два слэша должно быть, таков [стандарт json](http://json.org/)

**Comment by artbear** [comment]
Это не ошибка, а запланированное поведение.

ОФФ @dmpas ты шустрый :)

**Comment by artbear** [comment]
Но мне казалось, что у нашей реализации json был какой-то ключик для отключения такого поведения :)

**Comment by HardAndHeavy** [comment]
@dmpas , извиняюсь. Ошибка воспроизводится и при двух слэшах. Оригинальный код, на котором у меня это случилось был с двумя слэшами.

Переписал минимальный код:
```
#Использовать json

Процедура ВыполнитьКоманду()
	
	текстНастроек =
	"{
	|	""myString"": ""C:\\update_for_my_base.epf""
	|}";
	
	ЧтениеJSON = Новый ПарсерJSON;
	параметрыИзФайла = ЧтениеJSON.ПрочитатьJSON(текстНастроек,,,Истина);
	
	Сообщить(параметрыИзФайла["myString"]);

КонецПроцедуры

ВыполнитьКоманду();
```
так же падает с ошибкой

**Comment by HardAndHeavy** [comment]
Сузил ошибку до `\\up` если строка будет содержать такое начало, то всё будет плохо, например
`\\upp` или `\\upqwerty`

**Comment by dmpas** [comment]
видимо, он хочет отработать комбинацию "\uXXXX", игнорируя двойной слэш. тогда это косяк.

**Comment by EvilBeaver** [comment]
@HardAndHeavy спасибо за найденную "ошибку платформы" :)

**Comment by HardAndHeavy** [comment]
@EvilBeaver пожалуйста. Я можно сказать в первый раз на github. Хорошее у вас сообщество получилось. Очень тепло. Пока только разбираюсь и пользуюсь инструментами. Крутые вещи делаете, ребят @dmpas @artbear :)

**Comment by EvilBeaver** [comment]
Тут тех кто делает крутые вещи устанешь перечислять ) Присоединяйся.

**Comment by dmpas** [comment]
на последнем стабильном движке (1.0.16) канонический вариант с двумя слэшами теперь отрабатывает правильно. Спасибо.
