### ISSUE TITLE
Очепятка

### ISSUE THREAD

**Issue by tsukanov-as** [oscript-library/json#5]
https://github.com/oscript-library/json/blob/4b4a42118b1155cee83c8afc0529066ee69f3386/src/json.os#L1610

ИсключениеНеожиданноеОкончаниеОбъеТКа

**Comment by dmpas** [comment]
окончание "объедка".

**Comment by EvilBeaver** [comment]
Может сразу и пулреквест?

23 Авг 2017 г. 11:31 пользователь "Sergey Batanov" <notifications@github.com>
написал:

**Comment by artbear** [comment]
Исправлено. 1 минута или меньше
